import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

export function Privacy() {
  const navigate = useNavigate();

  return (
    <div
      style={{
        minHeight: '100vh',
        backgroundColor: '#f5f3ef',
        fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        color: '#1a1a1a',
      }}
    >
      {/* Header */}
      <header
        style={{
          borderBottom: '1px solid #e8e5df',
          backgroundColor: '#f5f3ef',
        }}
      >
        <div
          style={{
            maxWidth: 800,
            margin: '0 auto',
            padding: '0 32px',
            height: 64,
            display: 'flex',
            alignItems: 'center',
            gap: 16,
          }}
        >
          <button
            onClick={() => navigate('/')}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              padding: '6px 14px',
              fontSize: 13,
              fontWeight: 500,
              color: '#666',
              backgroundColor: '#fff',
              border: '1px solid #e8e5e0',
              borderRadius: 8,
              cursor: 'pointer',
              fontFamily: 'inherit',
            }}
          >
            <ArrowLeft size={14} />
            Back
          </button>
          <span style={{ fontSize: 14, fontWeight: 600, color: '#1a1a1a' }}>Privacy Policy</span>
        </div>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 800, margin: '0 auto', padding: '48px 32px 80px' }}>
        <h1 style={{ fontSize: 32, fontWeight: 700, marginBottom: 8 }}>Privacy Policy</h1>
        <p style={{ fontSize: 13, color: '#999', marginBottom: 40 }}>Last updated: February 14, 2026</p>

        <div style={{ fontSize: 15, color: '#444', lineHeight: 1.8 }}>
          <Section title="1. Introduction">
            <p>
              Masidy ("we", "our", "us") operates the Masidy Agent platform at masidy.com. This Privacy Policy
              describes how we collect, use, and protect your personal information when you use our service.
            </p>
            <p>
              By using Masidy Agent, you agree to the collection and use of information as described in this policy.
            </p>
          </Section>

          <Section title="2. Information We Collect">
            <h4 style={h4Style}>2.1 Account Information</h4>
            <p>When you sign up via GitHub OAuth, we collect:</p>
            <ul style={ulStyle}>
              <li>Your GitHub username and display name</li>
              <li>Your email address (from your GitHub account)</li>
              <li>Your GitHub profile avatar URL</li>
              <li>A GitHub access token (used only for repository operations you authorize)</li>
            </ul>

            <h4 style={h4Style}>2.2 Project Data</h4>
            <p>When you use Masidy Agent to build projects, we store:</p>
            <ul style={ulStyle}>
              <li>Project names and descriptions you provide</li>
              <li>Source code files generated by the AI agent</li>
              <li>Build logs and terminal output from your sessions</li>
              <li>Task history and prompts you submit</li>
            </ul>

            <h4 style={h4Style}>2.3 Usage Data</h4>
            <p>We automatically collect:</p>
            <ul style={ulStyle}>
              <li>Pages visited and features used within the platform</li>
              <li>Session duration and interaction patterns</li>
              <li>Browser type, device type, and operating system</li>
              <li>IP address (for security and abuse prevention)</li>
            </ul>
          </Section>

          <Section title="3. How We Use Your Information">
            <p>We use the information we collect to:</p>
            <ul style={ulStyle}>
              <li>Provide and maintain the Masidy Agent service</li>
              <li>Authenticate you and manage your account</li>
              <li>Execute AI-powered code generation on your behalf</li>
              <li>Push code to GitHub repositories when you request it</li>
              <li>Deploy your projects to hosting platforms (e.g., Vercel) when requested</li>
              <li>Improve the quality and performance of our AI agent</li>
              <li>Send important service updates and security notices</li>
              <li>Prevent fraud, abuse, and unauthorized access</li>
            </ul>
          </Section>

          <Section title="4. Third-Party Services">
            <p>Masidy Agent integrates with the following third-party services:</p>
            <ul style={ulStyle}>
              <li><strong>Anthropic (Claude API)</strong> — Your prompts are sent to Anthropic's Claude API to generate code. Anthropic's privacy policy applies to data processed by their models.</li>
              <li><strong>GitHub</strong> — Used for authentication and optional repository management. Subject to GitHub's privacy policy.</li>
              <li><strong>Vercel</strong> — Used for deploying your projects. Subject to Vercel's privacy policy.</li>
              <li><strong>Supabase</strong> — Used for file storage and database services.</li>
            </ul>
            <p>
              We do not sell your personal information to any third party. We only share data with the services
              listed above as necessary to operate the platform.
            </p>
          </Section>

          <Section title="5. Data Storage & Security">
            <p>
              Your data is stored on secure servers hosted by Render and Supabase. We implement
              industry-standard security measures including:
            </p>
            <ul style={ulStyle}>
              <li>Encrypted data transmission (HTTPS/TLS)</li>
              <li>Secure token-based authentication (JWT)</li>
              <li>Access controls and permission-based authorization</li>
              <li>Regular security audits of our codebase</li>
            </ul>
            <p>
              While we strive to protect your data, no method of electronic transmission or storage is 100% secure.
              We cannot guarantee absolute security.
            </p>
          </Section>

          <Section title="6. Your Rights">
            <p>You have the right to:</p>
            <ul style={ulStyle}>
              <li><strong>Access</strong> — Request a copy of the personal data we hold about you</li>
              <li><strong>Correction</strong> — Request correction of inaccurate data</li>
              <li><strong>Deletion</strong> — Request deletion of your account and associated data</li>
              <li><strong>Export</strong> — Download your project files and data</li>
              <li><strong>Withdraw consent</strong> — Revoke GitHub OAuth access at any time from your GitHub settings</li>
            </ul>
            <p>
              To exercise any of these rights, contact us at <a href="mailto:privacy@masidy.com" style={linkStyle}>privacy@masidy.com</a>.
            </p>
          </Section>

          <Section title="7. Cookies">
            <p>
              We use essential cookies and local storage to maintain your session, remember your preferences
              (such as enabled skills and theme settings), and keep you logged in. We do not use third-party
              tracking cookies or advertising cookies.
            </p>
          </Section>

          <Section title="8. Children's Privacy">
            <p>
              Masidy Agent is not intended for use by children under the age of 13. We do not knowingly collect
              personal information from children. If you believe a child has provided us with personal data,
              please contact us at <a href="mailto:privacy@masidy.com" style={linkStyle}>privacy@masidy.com</a>.
            </p>
          </Section>

          <Section title="9. Changes to This Policy">
            <p>
              We may update this Privacy Policy from time to time. We will notify you of significant changes by
              posting a notice on the platform or sending an email to your registered address. Your continued use
              of the service after changes take effect constitutes acceptance of the updated policy.
            </p>
          </Section>

          <Section title="10. Contact Us">
            <p>If you have questions about this Privacy Policy, contact us at:</p>
            <ul style={{ ...ulStyle, listStyle: 'none', paddingLeft: 0 }}>
              <li>Email: <a href="mailto:privacy@masidy.com" style={linkStyle}>privacy@masidy.com</a></li>
              <li>General: <a href="mailto:contact@masidy.com" style={linkStyle}>contact@masidy.com</a></li>
              <li>GitHub: <a href="https://github.com/masidytest/Autonomous" target="_blank" rel="noopener noreferrer" style={linkStyle}>github.com/masidytest/Autonomous</a></li>
            </ul>
          </Section>
        </div>
      </main>
    </div>
  );
}

const h4Style: React.CSSProperties = {
  fontSize: 14,
  fontWeight: 600,
  color: '#1a1a1a',
  marginTop: 20,
  marginBottom: 8,
};

const ulStyle: React.CSSProperties = {
  paddingLeft: 24,
  marginBottom: 16,
};

const linkStyle: React.CSSProperties = {
  color: '#7c3aed',
  textDecoration: 'none',
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 20, fontWeight: 700, color: '#1a1a1a', marginBottom: 12 }}>{title}</h2>
      {children}
    </section>
  );
}
